# For Github User
# github_username: "slack_member_id"

trevorliberty: "U01DFJBCQRX"
jjesse55: "U01D94PR39S"
jxm0428: 'U01D360RY8K'
numberTuu: 'U01CW7V2LA2'
t-john93: 'U01DSQQGSPJ'
sherretten: 'U01CZSRC3HT'
valdiston: 'U01D94PNN0L'
Yifan-Zhang618: 'U01D2VBT542'



# For Github Team
# github_teamname: "slack_member_id"
#  { id: 'U01CW7V2LA2', name: 'vutu', real_name: 'Tu Vu' },
#  {
#    id: 'U01CZSRC3HT',
#    name: 'sherrett',
#    real_name: 'Nathaniel Sherrett'
#  },
#  { id: 'U01D2VBT542', name: 'yifan', real_name: 'yifan' },
#  { id: 'U01D360RY8K', name: 'jiang6', real_name: 'Xiaomeng Jiang' },
#  {
#    id: 'U01D5LYCPGT',
#    name: 'integrations',
#    real_name: 'integrations'
#  },
#  { id: 'U01D94PNN0L', name: 'bjulian', real_name: 'Julian Baker' },
#  { id: 'U01D94PR39S', name: 'jjesse', real_name: 'Joseph Jesse' },
#  { id: 'U01D951GDTN', name: 'github', real_name: 'GitHub' },
#  { id: 'U01DFJBCQRX', name: 'tliberty', real_name: 'trevorliberty' },
#  { id: 'U01DFJQKMJM', name: 'simplepoll', real_name: 'Simple Poll' },
#  { id: 'U01DFJVSA4R', name: 'confluence', real_name: 'Confluence' },
#  { id: 'U01DSQQGSPJ', name: 'trevor29', real_name: 't-john' },
#  { id: 'U01DSR3BZEU', name: 'jirabot', real_name: 'Jira' }
