name: CI

# Controls when the action will run. Triggers the workflow on pull request
# events only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 3.7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip
          pip install -r requirements.txt

      # Execute test suite (unit & integration tests)
      - name: Unit/Integration Test Execution
        run: ./manage.py test tests/