# Continuous Integration github workflow yaml file
name: CI Tests

# Controls when the action will run. Triggers the workflow on pull request
# events only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          python3 -m pip install -r requirements.txt
      - name: Make Migrations
        run: python3 manage.py migrate

      # Execute python unit tests
      - name: Unit/Integration Test Execution
        run: python3 manage.py test tests/
      
      # Install selenium dependencies (chrome + webdriver)
      - name: Install Webdriver
        run: |
          mkdir ${HOME}/bin
          cd ${HOME}/bin
          wget https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          export PATH="${PATH}:${HOME}/bin"
        
      # Start Server
      - name: Start Server
        run: gunicorn --bind 0.0.0.0:8000 solenoid.wsgi
      
      # Execute Selenium Tests
      - name: Selenium Tests
        run: python3 manage.py test selenium_tests/
